version: '3'
services:
  php:
    build: ./docker/php/
    environment:
      TIMEZONE: Europe/Moscow
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./:/var/www/app
    working_dir: /var/www/app

  webserver:
    image: nginx:1.11
    depends_on:
      - php
    volumes:
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf:ro
      - ./:/var/www/app
    ports:
      - 8080:80

  composer:
    image: composer:1.9
    volumes:
      - ./:/var/www/app
    working_dir: /var/www/app
    command: install

  mydb:
    image: postgres
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - 5433:5432